[package]
name = "rssh-tunnel"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
inquire = "0.7.5"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-process = "0.2.5"
anyhow = "1.0.83"
structopt = "0.3.26"
